export const indonesianCities = [
  { name: 'Jakarta', code: 'CGK', fullName: 'Jakarta (CGK)' },
  { name: 'Surabaya', code: 'SUB', fullName: 'Surabaya (SUB)' },
  { name: 'Yogyakarta', code: 'YIA', fullName: 'Yogyakarta (YIA)' },
  { name: 'Denpasar', code: 'DPS', fullName: 'Denpasar (DPS)' },
  { name: 'Medan', code: 'KNO', fullName: 'Medan (KNO)' },
  { name: 'Makassar', code: 'UPG', fullName: 'Makassar (UPG)' },
  { name: 'Bandung', code: 'BDO', fullName: 'Bandung (BDO)' },
  { name: 'Semarang', code: 'SRG', fullName: 'Semarang (SRG)' },
  { name: 'Palembang', code: 'PLM', fullName: 'Palembang (PLM)' },
  { name: 'Balikpapan', code: 'BPN', fullName: 'Balikpapan (BPN)' },
  { name: 'Manado', code: 'MDC', fullName: 'Manado (MDC)' },
  { name: 'Lombok', code: 'LOP', fullName: 'Lombok (LOP)' },
  { name: 'Batam', code: 'BTH', fullName: 'Batam (BTH)' },
  { name: 'Pekanbaru', code: 'PKU', fullName: 'Pekanbaru (PKU)' },
  { name: 'Banjarmasin', code: 'BDJ', fullName: 'Banjarmasin (BDJ)' },
  { name: 'Pontianak', code: 'PNK', fullName: 'Pontianak (PNK)' },
  { name: 'Padang', code: 'PDG', fullName: 'Padang (PDG)' },
  { name: 'Malang', code: 'MLG', fullName: 'Malang (MLG)' },
  { name: 'Solo', code: 'SOC', fullName: 'Solo (SOC)' },
  { name: 'Jambi', code: 'DJB', fullName: 'Jambi (DJB)' },
];
